### PR TITLE
Category-rich post URLs

### PR DESCRIPTION
**Pull request by trevorblades**
This branch adds categories to the page URLs. It also reworks category pages a bit.

### CODE REVIEW

**Comment by stemmlerjs** [comment]
Thanks for this! Small adjustment - could we make the index page look more like this? Swap the header + subcategories and reduce the margin a 'lil bit?

Screen Shot 2021-05-11 at 11 27 04 PM

**Comment by stemmlerjs** [comment]
I also found a bug. Subcategories without posts shouldn't be shown/clickable. 

- Go here https://deploy-preview-17--apollographql-blog.netlify.app/backend/1
- Click "testing"
- Page doesn't exist

**Comment by stemmlerjs** [comment]
This leads me to ask, do you need me to first create and assign a post to a category + subcategory for us to test that this works?

**Comment by trevorblades** [comment]
Good idea @stemmlerjs! I adjusted the category page layout in the latest deploy preview. I also made it so that categories (and subcategories) won't show up in the UI if they don't have any posts.

**Comment by stemmlerjs** [comment]
@trevorblades Let's start with two examples to confirm this PR works. Here are two blog posts that can be used for testing.

**Example 1**: With category + subtopic
`/email-password-authentication-with-accounts-js-and-apollo-server/` → `/apollo-server/auth/email-password-authentication-with-accounts-js`

I expect to see:
- `apollo-server` category index page which also contains an `auth` subcategory

**Example 2**: With category only
`/join-us-for-apollo-day-in-nyc-and-san-francisco-in-may-8b43150f6fd4` → `/events/apollo-day-2019`

I expect to see:
- `events` category index page

**Comment by trevorblades** [comment]
Check em out! @stemmlerjs 🎉 

accounts-js post: https://deploy-preview-17--apollographql-blog.netlify.app/apollo-server/auth/email-password-authentication-with-accounts-js/
Apollo Server category: https://deploy-preview-17--apollographql-blog.netlify.app/apollo-server/1
Auth topic: https://deploy-preview-17--apollographql-blog.netlify.app/apollo-server/auth/1

Apollo Day post: https://deploy-preview-17--apollographql-blog.netlify.app/events/apollo-day-2019/
Events category: https://deploy-preview-17--apollographql-blog.netlify.app/events/1

**Comment by stemmlerjs** [comment]
Looks great @trevorblades! I think we're pretty much good to go. 
One last little thing. I just noticed that the post category/tags look a little bit wonky when they get lengthy.

Screen Shot 2021-05-14 at 10 32 17 AM

I'd recommend doing something like this:
Screen Shot 2021-05-14 at 10 35 56 AM

**Comment by trevorblades** [comment]
Good catch @stemmlerjs! Fixed: 
Screen Shot 2021-05-14 at 11 05 51 AM

**Comment by stemmlerjs** [comment]
Looks great @trevorblades 👍

**Review by stemmlerjs — APPROVED** [review]

**Pull request merged**
